version: "3.9"

services:
  uniswap-consumer:
    build:
      context: ./consumers
      dockerfile: Dockerfile
    container_name: uniswap-consumer
    depends_on:
      - kafka
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=ozi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    networks:
      - ozi-net

  uniswap-listener:
    build:
      context: ./producers
      dockerfile: Dockerfile
    container_name: uniswap-listener
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - KAFKA_BROKER=kafka:29092
    volumes:
      - ./producers/configs:/app/configs
    networks:
      - ozi-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ozi-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - ozi-net
    
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ozi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ozi-net
volumes:
  pgdata:

networks:
  ozi-net:
    driver: bridge