[pair]
name = "USDC-ETH-0.05"

[pool]
address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"

[kafka]
bootstrap_servers = "kafka:29092"

[[abi]]
type = "event"
name = "Swap"
anonymous = false

  [[abi.inputs]]
  indexed = true
  internalType = "address"
  name = "sender"
  type = "address"

  [[abi.inputs]]
  indexed = true
  internalType = "address"
  name = "recipient"
  type = "address"

  [[abi.inputs]]
  indexed = false
  internalType = "int256"
  name = "amount0"
  type = "int256"

  [[abi.inputs]]
  indexed = false
  internalType = "int256"
  name = "amount1"
  type = "int256"

  [[abi.inputs]]
  indexed = false
  internalType = "uint160"
  name = "sqrtPriceX96"
  type = "uint160"

  [[abi.inputs]]
  indexed = false
  internalType = "uint128"
  name = "liquidity"
  type = "uint128"

  [[abi.inputs]]
  indexed = false
  internalType = "int24"
  name = "tick"
  type = "int24"